### ISSUE TITLE
can fix it ? 

### ISSUE THREAD

**Issue by eihwazonyx** [H4vC/PoeHud#62]
poeHud work very well on my window 7 

since i upgrade to 10 it continue it doesn't work anymore 

error 

8/2/2015 11:03 AM Program exited with message:
 System.Exception: You should run program as an administrator ---> System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at PoeHUD.Framework.Memory..ctor(Offsets offs, Int32 pId)
   --- End of inner exception stack trace ---
   at PoeHUD.Framework.Memory..ctor(Offsets offs, Int32 pId)
##    at PoeHUD.Program.Main(String[] args)

8/2/2015 11:10 AM Program exited with message:
 System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PoeHUD.Poe.FilesInMemory.ModsDat.ModRecord..ctor(Memory m, StatsDat sDat, TagsDat tagsDat, Int32 addr)
   at PoeHUD.Poe.FilesInMemory.ModsDat.loadItems(StatsDat sDat, TagsDat tagsDat)
   at PoeHUD.Poe.FilesInMemory.ModsDat..ctor(Memory m, Int32 address, StatsDat sDat, TagsDat tagsDat)
   at PoeHUD.Controllers.FsController..ctor(Memory mem)
   at PoeHUD.Controllers.GameController..ctor(Memory memory)

**Comment by eihwazonyx** [comment]
![image](https://cloud.githubusercontent.com/assets/13607086/9026198/ff8f567c-3950-11e5-9845-e41541637824.png)

**Comment by NightAura** [comment]
Turn off your Anti Virus/Malware programs?

**Comment by H4vC** [comment]
You should be running this as admin, issue closed.

**Comment by eihwazonyx** [comment]
hello my computor doen'thave any anti-virus 

and secound error show up when i try to run as admin

**Comment by eihwazonyx** [comment]
wow i don't know how but now fix it

**Comment by eihwazonyx** [comment]
ty guyss XD
