### ISSUE TITLE
Crashes on Steam Client

### ISSUE THREAD

**Issue by bibabaluba** [H4vC/PoeHud#83]
Heya, Great addon, but doesn't work anymore in maps/area's. Does still work in Encampments, but as soon as you enter area, I get the following error. (Previous versions worked. Never had issues.)

System.TypeLoadException: Could not load type 'System.Numerics.Matrix4x4' from assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at PoeHUD.Poe.RemoteMemoryObjects.Camera.WorldToScreen(Vector3 vec3, EntityWrapper entityWrapper)
   at PoeHUD.Hud.Health.HealthBarPlugin.Render()
   at PoeHUD.Hud.ExternalOverlay.<>c.<OnRender>b__21_0(IPlugin x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PoeHUD.Hud.ExternalOverlay.OnRender()
   at PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   at PoeHUD.Hud.UI.Graphics.RenderLoop()
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>b__20_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

Keep up the great work guys!!!

**Comment by ghost** [comment]
You need Microsoft .NET Framework 4.6.
https://www.microsoft.com/en-us/download/details.aspx?id=48130

If you can't use 4.6, just disable Healhtbars.

**Comment by bibabaluba** [comment]
Hi, thanks for reply. I reinstalled 4.6 and that helped. Thanks for the tip :) Works again. Keep up the awesome work. I love the new looks. Any thoughts of adding mods you can craft on the item using the masters?
